### PR TITLE
Cleanup Readme and Add Wind to Hourly

### LINKED ISSUE #91: Wind speed in forecast attribute?
Looks like the forecast attributes in HA only have the following sensors:
forecast:
  - datetime: '2023-03-25T20:00:00+00:00'
    precipitation_probability: 88
    condition: rainy
    temperature: 38
    precipitation: 0.02

Is there any way to add wind speed to this?  I do a calculation to come up with wind chill (https://www.weather.gov/epz/wxcalc_windchill) and graph out the forecasts.

Thanks!

### LINKED ISSUE #102: DarkSky HA Integration Removed - Dead Documentation Links
The DarkSky integrations have been removed from HA so the links in the documentation section take you to page which states that the integration has been removed. A quick fix would be to use the WayBackMachine to replace the links but having your own docs would be beneficial.

### PR DESCRIPTION
**Pull request by cloneofghosts**
Removed links to page which either are redirects to other pages or have been removed. Added Wayback Machine links for documentation since there is no complete HA documentation on the PW site which should be added in the future. This fixes #102 and is also mentioned in this issue https://github.com/alexander0042/pirateweather/issues/33.

Add Wind Speed to Forecast Attributes and fixes #91.

### CODE REVIEW

**Comment by cloneofghosts** [comment]
@alexander0042 I did the same thing here that I did in the processing code repo where any links to the DarkSky HA code/documentation have been removed.

I also added in Wind Speed & Wind Direction into hourly since the issue I linked to had the steps to add it and they say it works without issues. I can remove that if you want me to.

**Comment by cloneofghosts** [comment]
I added text which might help users solve the AttributeError: PRECIPITATION errors they might get upon import if they are running an older version of HA. I think it was added in 2022.12 but I'm not 100% sure on that.

**Comment by alexander0042** [comment]
Just went from that issue over here and I see you've already added that in the README! These are all amazing changes, and I'm going to roll them all out in a new version shortly

**Comment by cloneofghosts** [comment]
@alexander0042 I had added the text before you investigated to see which version the precipitation classes were added. You might want to change 2022.12 to 2022.10 if that is the correct version the classes were added in.

**Comment by alexander0042** [comment]
Already done 😊!

**Pull request merged**
